# Generated by Django 3.2.6 on 2021-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_auto_20210911_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_countries',
        ),
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='book_outlet.Country'),
        ),
    ]
